import UserHeader from "@/app/components/user-header/user-header"
import './profile.css'

export const metadata = {
  title: 'NetGuardian',
  description: 'Generated by create next app',
}

export default function ProfileLayout({ children }) {
  return (
    <>
      <UserHeader/>
      <main>
        {children}
      </main>
    </>
    
  )
}
