import { Inter } from 'next/font/google'
import './globals.css'
import BasicHeader from './components/header/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NetGuardian',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      <BasicHeader/>
      <main>{children}</main>
    </>
    
  )
}
