import TopMenu from "@/app/components/top-menu/top-menu"
import UserHeader from "@/app/components/user-header/user-header"
import './home.css'

export const metadata = {
  title: 'NetGuardian',
  description: 'Generated by create next app',
}

export default function HomeLayout({ children }) {
  return (
    <>
      <UserHeader/>
      <TopMenu/>
      <main>{children}</main>
    </>
    
  )
}
