import TopMenu from "@/app/components/top-menu/top-menu"

export const metadata = {
  title: 'NetGuardian',
  description: 'Generated by create next app',
}

export default function HomeLayout({ children }) {
  return (
    <>
      <TopMenu/>
      <main>{children}</main>
    </>
    
  )
}
